jared = User.create(name: "Jared Shelby", email: "jared.shelby@yale.edu")

Milestone.create(name: "Ski Trip", amount: 2000, funded: 0, description: "Can't wait to go to the alps!", target: "August 8, 2022", image: "https://media.cntraveler.com/photos/5f84939a5f9755e5951db3f4/master/pass/WhitefishMountainResort-3.jpg", user: jared)
Milestone.create(name: "New House", amount: 40000, funded: 0, description: "Down payment for our future forever home <3.", target: "December 18, 2022", image: "https://foyr.com/learn/wp-content/uploads/2021/08/design-your-dream-home.jpg", user: jared)
Milestone.create(name: "Summer Funds", amount: 300, funded: 0, description: "Just want a little money for the summer.", target: "August 22, 2022", image: "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/beautiful-tropical-sunset-scenery-two-sun-beds-royalty-free-image-1595368231.jpg", user: jared)
Milestone.create(name: "Flowers", amount: 50, funded: 0, description: "Looking to treat myself :).", target: "September 2, 2022", image: "https://www.farmersalmanac.com/wp-content/uploads/2021/04/forget-me-not-flower-as309740666.jpeg", user: jared)

food_drink = Category.create(name: "Food/Drink")
entertainment = Category.create(name: "Entertainment")
bills = Category.create(name: "Bills")
health_beauty = Category.create(name: "Health/Beauty")
transportation = Category.create(name: "Transportation")
shopping = Category.create(name: "Shopping")
other = Category.create(name: "Other")

Transaction.create(amount: 4.56, date: "August 3, 2022", merchant: "Coffee Bean", user: jared, category: food_drink)
Transaction.create(amount: 15.67, date: "July 13, 2022", merchant: "Theater Delight", user: jared, category: entertainment)
Transaction.create(amount: 180, date: "August 1, 2022", merchant: "Zap Electric", user: jared, category: bills)
Transaction.create(amount: 50.60, date: "August 1, 2022", merchant: "Mobile Madness", user: jared, category: bills)
Transaction.create(amount: 156.78, date: "June 20, 2022", merchant: "SY Hospital", user: jared, category: health_beauty)
Transaction.create(amount: 35, date: "June 24, 2022", merchant: "ByeBye Train", user: jared, category: transportation)
Transaction.create(amount: 100.09, date: "July 18, 2022", merchant: "Skymart", user: jared, category: shopping)
